
using PactNet;
using PactNet.Infrastructure.Outputters;

namespace SampleProvider.Tests
{
    public class ProviderContractTests
    {
        [Fact]
        public void EnsureProviderHonoursPactWithConsumer()
        {
            // Path to local pact file generated by the consumer tests
            var pactPath = Path.Combine("pacts", "sampleconsumer-sampleprovider.json");

            var config = new PactVerifierConfig
            {
                Outputters = new IOutput[]
                {
                    new ConsoleOutput()
                },
                Verbose = true
            };

            var pactVerifier = new PactVerifier(config);

            pactVerifier
                .ServiceProvider("SampleProvider", "http://localhost:5000")
                .HonoursPactWith("SampleConsumer")
                .PactUri(pactPath)
                .Verify();
        }
    }

    public class ConsoleOutput : IOutput
    {
        public void WriteLine(string line)
        {
            Console.WriteLine(line);
        }
    }
}
